
package introsde.document.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Goals", targetNamespace = "http://ws.document.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Goals {


    /**
     * 
     * @param idPerson
     * @return
     *     returns introsde.document.ws.Goal
     */
    @WebMethod
    @WebResult(name = "message", targetNamespace = "")
    @RequestWrapper(localName = "getGoalByIdPerson", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.GetGoalByIdPerson")
    @ResponseWrapper(localName = "getGoalByIdPersonResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.GetGoalByIdPersonResponse")
    @Action(input = "http://ws.document.introsde/Goals/getGoalByIdPersonRequest", output = "http://ws.document.introsde/Goals/getGoalByIdPersonResponse")
    public Goal getGoalByIdPerson(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.document.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "readGoalList", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadGoalList")
    @ResponseWrapper(localName = "readGoalListResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadGoalListResponse")
    @Action(input = "http://ws.document.introsde/Goals/readGoalListRequest", output = "http://ws.document.introsde/Goals/readGoalListResponse")
    public List<Goal> readGoalList();

    /**
     * 
     * @param goal
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "message", targetNamespace = "")
    @RequestWrapper(localName = "createGoal", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.CreateGoal")
    @ResponseWrapper(localName = "createGoalResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.CreateGoalResponse")
    @Action(input = "http://ws.document.introsde/Goals/createGoalRequest", output = "http://ws.document.introsde/Goals/createGoalResponse")
    public int createGoal(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal);

    /**
     * 
     * @param goal
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "goalId", targetNamespace = "")
    @RequestWrapper(localName = "updateGoal", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.UpdateGoal")
    @ResponseWrapper(localName = "updateGoalResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.UpdateGoalResponse")
    @Action(input = "http://ws.document.introsde/Goals/updateGoalRequest", output = "http://ws.document.introsde/Goals/updateGoalResponse")
    public int updateGoal(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal);

    /**
     * 
     * @param idGoal
     * @return
     *     returns introsde.document.ws.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "readGoal", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadGoal")
    @ResponseWrapper(localName = "readGoalResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.ReadGoalResponse")
    @Action(input = "http://ws.document.introsde/Goals/readGoalRequest", output = "http://ws.document.introsde/Goals/readGoalResponse")
    public Goal readGoal(
        @WebParam(name = "idGoal", targetNamespace = "")
        int idGoal);

    /**
     * 
     * @param goalId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "message", targetNamespace = "")
    @RequestWrapper(localName = "deleteGoal", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.DeleteGoal")
    @ResponseWrapper(localName = "deleteGoalResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.DeleteGoalResponse")
    @Action(input = "http://ws.document.introsde/Goals/deleteGoalRequest", output = "http://ws.document.introsde/Goals/deleteGoalResponse")
    public int deleteGoal(
        @WebParam(name = "goalId", targetNamespace = "")
        int goalId);

}
